input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "metrics/metric.json"
splitting_params:
  test_size: 0.3
  random_state: 42
  shuffle: True
feature_params:
  numerical_columns:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  categorical_columns:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  columns_to_drop: null
  target_column: "condition"
  fill_na_numerical_strategy: "mean"
  fill_na_categorical_strategy: "most_frequent"
training_params:
  model: "LogisticRegression"
  random_state: 42
  model_params:
    penalty: 'none'